// Package model defines the shared data types passed between gather and render stages.
package model

import (
	"os"
	"path/filepath"
	"time"

	"github.com/kylesnowschwartz/agent-ouija/claude/statusline"
)

// RenderContext is the central struct passed from the gather stage to each render widget.
// Every pointer field may be nil — widgets must guard against nil before dereferencing.
type RenderContext struct {
	TerminalWidth int
	SessionStart  string

	// Top-level fields populated from StdinData during the gather stage.
	// Widgets read these directly rather than dereferencing pointer fields.
	ModelID           string
	ModelDisplayName  string
	ContextWindowSize int
	ContextPercent    int
	Cwd               string

	// Token fields populated from StdinData.ContextWindow.CurrentUsage.
	InputTokens   int
	CacheCreation int
	CacheRead     int

	// Cost and duration fields from StdinData.Cost.
	// SessionCostUSD is 0 when no cost data is available.
	// TotalDurationMs is the authoritative session duration from Claude Code;
	// prefer it over transcript-derived duration when non-zero.
	SessionCostUSD  float64
	TotalDurationMs int
	APIDurationMs   int
	LinesAdded      int
	LinesRemoved    int

	// OutputStyle is the current output style name (e.g. "auto", "verbose").
	// Empty string when not provided by Claude Code.
	OutputStyle string

	// WorktreeName is the name of the current worktree, if any.
	// Empty when not running inside a worktree.
	WorktreeName string

	// WorktreeBranch is the branch checked out in the current worktree.
	// Empty when not in a worktree or when the branch is unavailable.
	WorktreeBranch string

	// EffortLevel is the current reasoning effort ("low", "medium", "high",
	// "xhigh", "max"). Empty when Claude Code does not report it.
	EffortLevel string

	// ExtraOutput is the label returned by the user's extra command.
	// Empty when no extra command is configured or the command fails/times out.
	ExtraOutput string

	// PermissionProject is the project name (last path component of CWD) of
	// another Claude Code session that appears to be blocked waiting for user
	// permission approval. Empty when no session needs attention.
	PermissionProject string

	// PeerCount is the number of other live interactive Claude Code sessions
	// read from the native session registry (~/.claude/sessions). Zero when
	// none, or when the peers widget is not configured.
	PeerCount int

	// Pointer fields — all may be nil when the corresponding data is unavailable.
	Transcript *TranscriptData
	EnvCounts  *EnvCounts
	Git        *GitStatus

	// Usage holds rate-limit utilization data from stdin.
	// Nil when rate_limits is absent from stdin (older Claude Code or API users)
	// or when the usage widget is not configured.
	Usage *UsageInfo
}

// UsageInfo holds rate-limit utilization data from stdin for rendering.
// FiveHourPercent and SevenDayPercent are -1 when unavailable.
type UsageInfo struct {
	FiveHourPercent int       `json:"five_hour_percent"` // 0-100, or -1
	FiveHourResetAt time.Time `json:"five_hour_reset_at"`
	SevenDayPercent int       `json:"seven_day_percent"` // 0-100, or -1
	SevenDayResetAt time.Time `json:"seven_day_reset_at"`
}

// TokenSample records a token count observation at a point in time.
// It is used by the speed widget to compute a rolling tokens/sec average.
type TokenSample struct {
	Timestamp time.Time
	Tokens    int // output tokens generated by a single API response
}

// TranscriptData holds parsed information from the Claude Code transcript.
type TranscriptData struct {
	Path        string
	SessionName string
	Tools       []ToolEntry
	Agents      []AgentEntry
	Todos       []TodoItem
	// SkillNames is the ordered list of skill names invoked in the session
	// (newest last), capped at 20. Each entry is the skill name extracted
	// from <command-name>/skill</command-name> tags in user messages.
	SkillNames []string

	// TokenSamples holds timestamp+token pairs extracted from assistant messages.
	// Used by the speed widget to compute a rolling tokens/sec average.
	TokenSamples []TokenSample

	// ThinkingActive is true when the most recent assistant message contained a
	// thinking block that was not followed by a tool_use or text block in the
	// same message.
	ThinkingActive bool

	// ThinkingCount is the total number of thinking blocks observed across all
	// assistant messages in the session.
	ThinkingCount int

	// SpinnerFrame is a monotonic counter incremented on each statusline invocation.
	// Widgets use it instead of wall-clock time to guarantee spinner advancement
	// on every render regardless of when within a tick the binary runs.
	SpinnerFrame int

	// DividerOffset is a monotonic counter incremented once per new tool_use.
	// The tools widget uses it to highlight one separator: position = offset %
	// (numVisible - 1). This creates a scrolling ticker effect where the
	// highlighted divider advances with each new tool call and wraps around.
	DividerOffset int

	// MessageCount is the number of user/assistant conversational turns in the
	// transcript, excluding pure tool_result entries.
	MessageCount int
}

// ToolEntry records a single tool invocation observed in the transcript.
type ToolEntry struct {
	Name       string
	Completed  bool      // false = still running, true = completed or error
	DurationMs int       // 0 = still running or unknown
	HasError   bool      // true when the tool_result had is_error set
	Category   string    // file, shell, search, web, agent, internal
	Target     string    // file path, command, pattern, or other contextual string
	StartTime  time.Time // when the tool_use was first observed in the transcript
}

// AgentEntry records a sub-agent task observed in the transcript.
type AgentEntry struct {
	ID          string // hex UUID from the agent filename or tool_use block ID
	Name        string
	Status      string
	Model       string    // e.g. "claude-haiku-4-5"
	Description string    // agent task description from the tool input
	ColorIndex  int       // 0-7, assigned by first-appearance order (index % 8)
	StartTime   time.Time // when the agent tool_use was observed
	DurationMs  int       // 0 = still running; populated by a separate card
}

// TodoItem represents a todo entry from the Claude Code session.
type TodoItem struct {
	ID      string
	Content string
	Done    bool
}

// EnvCounts holds counts of active Claude Code environment config items,
// broken down by category.
type EnvCounts struct {
	MCPServers    int // unique MCP server names across all settings files
	ClaudeMdFiles int // CLAUDE.md files found at standard paths
	RuleFiles     int // .md files under ~/.claude/rules and {cwd}/.claude/rules
	Hooks         int // non-empty hook event arrays across settings files
}

// GitStatus holds the current git repository state for the working directory.
type GitStatus struct {
	Branch    string
	Dirty     bool
	AheadBy   int
	BehindBy  int
	Untracked int
	Modified  int
	Staged    int

	// LinesAdded/LinesRemoved are the uncommitted line deltas vs HEAD
	// (staged + unstaged; untracked files excluded). Populated only when
	// the working tree is dirty.
	LinesAdded   int
	LinesRemoved int
}

// IsDirty reports whether the working tree has any uncommitted changes
// (dirty flag, modified files, staged files, or untracked files).
func (g *GitStatus) IsDirty() bool {
	return g.Dirty || g.Modified > 0 || g.Staged > 0 || g.Untracked > 0
}

// StdinData is the statusline stdin document plus HUD-computed fields.
// The wire schema (session, model, context window, cost, rate limits,
// worktree, effort, ...) lives in the agent-ouija statusline package;
// its fields promote through the embedding.
type StdinData struct {
	statusline.Payload

	// ContextPercent is computed by the stdin package — not decoded from JSON.
	ContextPercent int `json:"-"`
}

// PluginDir returns the directory used for plugin state files:
// ~/.claude/plugins/tail-claude-hud/
// Falls back to os.TempDir() if the home directory cannot be resolved.
func PluginDir() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return os.TempDir()
	}
	return filepath.Join(home, ".claude", "plugins", "tail-claude-hud")
}
